[package]
name = "radiant-rs"
version = "0.1.0"
authors = ["Dennis Möhlmann <dmo479@gmail.com>"]

[dependencies]
glium = "*"
image = "*"
regex = "*"
lazy_static = "*"
num = "*"
rusttype = "0.2.1"
unicode-normalization = "0.1.0"
font-loader = "*"

[lib]
name = "radiant_rs"
path = "src/lib.rs"

[[bin]]
doc = false
name = "demos"
path = "src/main.rs"

[[example]]
name = "blobs"
path = "src/examples/blobs.rs"

[[example]]
name = "threads"
path = "src/examples/threads.rs"
