[package]
name = "radiant-rs"
version = "0.3.0"
authors = ["Dennis Möhlmann <dmo479@gmail.com>"]
description = "Thread-safe Rust sprite rendering engine with a friendly API and custom shader support"
documentation = "https://sinesc.github.io/doc/radiant_rs/"
repository = "https://github.com/sinesc/radiant-rs.git"
license = "MIT"

[dependencies]
glium = "0.15.0"
image = "0.10.3"
regex = "0.1.73"
lazy_static = "0.2.1"
num = "0.1.34"
rusttype = "0.2.1"
unicode-normalization = "0.1.2"
font-loader = "0.1.0"
enum_primitive = "0.1.0"
avec = "0.1.0"
palette = "0.2.1"

[lib]
name = "radiant_rs"
path = "src/lib.rs"

[[bin]]
doc = false
name = "demos"
path = "src/main.rs"

[[example]]
name = "01_empty"
path = "examples/01_empty.rs"

[[example]]
name = "02_sprites"
path = "examples/02_sprites.rs"

[[example]]
name = "03_text"
path = "examples/03_text.rs"

[[example]]
name = "04_postprocessor"
path = "examples/04_postprocessor.rs"

[[example]]
name = "05_matrix"
path = "examples/05_matrix.rs"

[[example]]
name = "06_threads"
path = "examples/06_threads.rs"

[[example]]
name = "99_scene"
path = "examples/99_scene.rs"


[[example]]
name = "demo_blobs"
path = "examples/demo_blobs.rs"

[[example]]
name = "demo_glare"
path = "examples/demo_glare.rs"
