[package]
name = "radiant-rs"
version = "0.1.0"
authors = ["Dennis Möhlmann <dmo479@gmail.com>"]

[lib]
name = "radiant_rs"
path = "src/lib.rs"

[[bin]]
doc = false
name = "demos"
path = "src/main.rs"

[dependencies]
glium = "*"
image = "*"
regex = "*"
lazy_static = "*"
num = "*"
rusttype = "0.2.1"
unicode-normalization = "0.1.0"
font-loader = "*"
