[package]
name = "radiant-rs"
version = "0.2.0"
authors = ["Dennis Möhlmann <dmo479@gmail.com>"]
description = "Easy to use, thread-safe sprite rendering engine"
documentation = "https://sinesc.github.io/doc/radiant_rs/"
repository = "https://github.com/sinesc/radiant-rs.git"
license = "MIT"

[dependencies]
glium = "0.15.0"
image = "0.10.3"
regex = "0.1.73"
lazy_static = "0.2.1"
num = "0.1.34"
rusttype = "0.2.1"
unicode-normalization = "0.1.2"
font-loader = "0.1.0"
enum_primitive = "0.1.0"
avec = "0.1.0"
palette = "0.2.1"
#avec = { path = "../avec/" }

[lib]
name = "radiant_rs"
path = "src/lib.rs"

[[bin]]
doc = false
name = "demos"
path = "src/main.rs"

[[example]]
name = "blobs"
path = "examples/blobs.rs"

[[example]]
name = "threads"
path = "examples/threads.rs"

[[example]]
name = "minimalistic"
path = "examples/minimalistic.rs"

[[example]]
name = "scene"
path = "examples/scene.rs"

[[example]]
name = "postprocess"
path = "examples/postprocess.rs"
