[package]
name = "radiant-rs"
version = "0.1.0"
authors = ["Dennis Möhlmann <dmo479@gmail.com>"]
description = "Easy to use, thread-safe sprite rendering engine"
documentation = "https://sinesc.github.io/doc/radiant_rs/"
repository = "https://github.com/sinesc/radiant-rs.git"
license = "MIT"

[dependencies]
glium = "0.15.0"
image = "0.10.3"
regex = "0.1.73"
lazy_static = "0.2.1"
num = "0.1.34"
rusttype = "0.2.1"
unicode-normalization = "0.1.2"
font-loader = "0.1.0"

[lib]
name = "radiant_rs"
path = "src/lib.rs"

[[bin]]
doc = false
name = "demos"
path = "src/main.rs"

[[example]]
name = "blobs"
path = "src/examples/blobs.rs"

[[example]]
name = "threads"
path = "src/examples/threads.rs"

[[example]]
name = "minimalistic"
path = "src/examples/minimalistic.rs"
